"""
Compound Skill: skill.camera_capture_tts
Auto-generated by CCOS Skill Recombiner
Source pattern: ('vision.camera_capture', 'speech.tts')
Created: 2026-07-29 00:16:37
"""

import time
from typing import Any, Dict, List


def run(input_data: Any = None) -> Dict[str, Any]:
    """
    Execute compound skill: skill.camera_capture_tts
    Steps: vision.camera_capture -> speech.tts
    """
    results = {}
    total_start = time.time()
    step_results = []

    # Step 0: vision.camera_capture
    step_0_start = time.time()
    try:
        step_0_input = input_data if 0 == 0 else step_results[-1]
        step_0_result = _execute_step("vision.camera_capture", step_0_input)
        step_0_dur = (time.time() - step_0_start) * 1000
        step_results.append(step_0_result)
        results["step_0"] = {
            "capability": "vision.camera_capture",
            "result": step_0_result,
            "duration_ms": step_0_dur,
            "success": True,
        }
    except Exception as e:
        step_0_dur = (time.time() - step_0_start) * 1000
        results["step_0"] = {
            "capability": "vision.camera_capture",
            "error": str(e),
            "duration_ms": step_0_dur,
            "success": False,
        }
        # Continue pipeline even on failure
        step_results.append({"error": str(e)})

    # Step 1: speech.tts
    step_1_start = time.time()
    try:
        step_1_input = input_data if 1 == 0 else step_results[0]
        step_1_result = _execute_step("speech.tts", step_1_input)
        step_1_dur = (time.time() - step_1_start) * 1000
        step_results.append(step_1_result)
        results["step_1"] = {
            "capability": "speech.tts",
            "result": step_1_result,
            "duration_ms": step_1_dur,
            "success": True,
        }
    except Exception as e:
        step_1_dur = (time.time() - step_1_start) * 1000
        results["step_1"] = {
            "capability": "speech.tts",
            "error": str(e),
            "duration_ms": step_1_dur,
            "success": False,
        }
        # Continue pipeline even on failure
        step_results.append({"error": str(e)})

    total_ms = (time.time() - total_start) * 1000
    successes = sum(1 for r in results.values() if r.get("success"))
    return {
        "skill": "skill.camera_capture_tts",
        "steps_completed": len(results),
        "steps_succeeded": successes,
        "success": successes == len(results),
        "total_duration_ms": total_ms,
        "step_details": results,
    }


def _execute_step(capability: str, input_data: Any) -> Any:
    """Execute a single capability step."""
    import sys
    from pathlib import Path
    sys.path.insert(0, str(Path(__file__).parent.parent.parent.parent))
    from ccos.core.plugin_manager import get_plugin_manager
    pm = get_plugin_manager()
    pm.load_all()
    return pm.call_capability(capability)


def test():
    """Self-test: verify all step capabilities are available."""
    import sys
    from pathlib import Path
    sys.path.insert(0, str(Path(__file__).parent.parent.parent.parent))
    from ccos.core.plugin_manager import get_plugin_manager
    from ccos.core.capability_registry import get_capability_registry
    pm = get_plugin_manager()
    pm.load_all()
    registry = get_capability_registry()
    for step in ["vision.camera_capture", "speech.tts"]:
        if not registry.has(step):
            return False, f"Missing capability: {step}"
    return True, "All capabilities available"