"""CCOS capability entry points for the Termux API tool registry."""

from .termux_api import get_termux_api


def device_battery(**kwargs): return get_termux_api().execute("device.battery", **kwargs)
def device_brightness(**kwargs): return get_termux_api().execute("device.brightness", **kwargs)
def device_camera_info(**kwargs): return get_termux_api().execute("device.camera_info", **kwargs)
def device_camera_photo(**kwargs): return get_termux_api().execute("device.camera_photo", **kwargs)
def device_camera_record(**kwargs): return get_termux_api().execute("device.camera_record", **kwargs)
def device_clipboard_get(**kwargs): return get_termux_api().execute("device.clipboard_get", **kwargs)
def device_clipboard_set(**kwargs): return get_termux_api().execute("device.clipboard_set", **kwargs)
def device_contact_list(**kwargs): return get_termux_api().execute("device.contact_list", **kwargs)
def device_dialog(**kwargs): return get_termux_api().execute("device.dialog", **kwargs)
def device_location(**kwargs): return get_termux_api().execute("device.location", **kwargs)
def device_microphone_record(**kwargs): return get_termux_api().execute("device.microphone_record", **kwargs)
def device_microphone_info(**kwargs): return get_termux_api().execute("device.microphone_info", **kwargs)
def device_notification(**kwargs): return get_termux_api().execute("device.notification", **kwargs)
def device_notification_remove(**kwargs): return get_termux_api().execute("device.notification_remove", **kwargs)
def device_sensor_list(**kwargs): return get_termux_api().execute("device.sensor_list", **kwargs)
def device_sensor_read(**kwargs): return get_termux_api().execute("device.sensor_read", **kwargs)
def device_share(**kwargs): return get_termux_api().execute("device.share", **kwargs)
def device_sms_list(**kwargs): return get_termux_api().execute("device.sms_list", **kwargs)
def device_sms_send(**kwargs): return get_termux_api().execute("device.sms_send", **kwargs)
def device_storage_get(**kwargs): return get_termux_api().execute("device.storage_get", **kwargs)
def device_storage_scan(**kwargs): return get_termux_api().execute("device.storage_scan", **kwargs)
def device_torch(**kwargs): return get_termux_api().execute("device.torch", **kwargs)
def device_tts_speak(**kwargs): return get_termux_api().execute("device.tts_speak", **kwargs)
def device_tts_engines(**kwargs): return get_termux_api().execute("device.tts_engines", **kwargs)
def device_vibrate(**kwargs): return get_termux_api().execute("device.vibrate", **kwargs)
def device_volume(**kwargs): return get_termux_api().execute("device.volume", **kwargs)
def device_wallpaper(**kwargs): return get_termux_api().execute("device.wallpaper", **kwargs)
def device_wifi_connection(**kwargs): return get_termux_api().execute("device.wifi_connection", **kwargs)
def device_wifi_scan(**kwargs): return get_termux_api().execute("device.wifi_scan", **kwargs)
def device_wifi_enable(**kwargs): return get_termux_api().execute("device.wifi_enable", **kwargs)
def device_telephony_deviceinfo(**kwargs): return get_termux_api().execute("device.telephony_deviceinfo", **kwargs)
def device_telephony_cellinfo(**kwargs): return get_termux_api().execute("device.telephony_cellinfo", **kwargs)
def device_telephony_call(**kwargs): return get_termux_api().execute("device.telephony_call", **kwargs)
def device_usb(**kwargs): return get_termux_api().execute("device.usb", **kwargs)
def device_job_scheduler(**kwargs): return get_termux_api().execute("device.job_scheduler", **kwargs)
def network_download(**kwargs): return get_termux_api().execute("network.download", **kwargs)
def network_websearch(**kwargs): return get_termux_api().execute("network.websearch", **kwargs)
def network_open_url(**kwargs): return get_termux_api().execute("network.open_url", **kwargs)
def hardware_ir_transmit(**kwargs): return get_termux_api().execute("hardware.ir_transmit", **kwargs)
def speech_to_text(**kwargs): return get_termux_api().execute("speech.to_text", **kwargs)
def device_notification_list(**kwargs): return get_termux_api().execute("device.notification_list", **kwargs)
